### ISSUE TITLE
List of Listings

### ISSUE THREAD

**Issue by HowDoIWalk** [nasa/nasa-latex-docs#5]
Would it be possible to add a command that creates a list of listings in the doc.  Similar to the List of Tables and List of Figures in the preamble.

**Comment by walshahi** [comment]
Pull the latest and try now. `\docLOL[true]` will now enable a "List of Code Listings". This is defaulted to `true` for `template=tech-report` and to `false` for `template=tech-memo`

**Comment by HowDoIWalk** [comment]
It works! And it's gloorrrrrrriousssssss!
