### ISSUE TITLE
Add SBU yellow sheet options

### ISSUE THREAD

**Issue by karenBibb** [nasa/nasa-latex-docs#9]
Templates should have the option of adding the yellow SBU cover sheet with options properly filled out.  

This file appears to have current electronic form for vertical layouts.
[NF1686.pdf](https://github.com/nasa/nasa-latex-docs/files/3989648/NF1686.pdf)

Note that the last security training I did hinted that they would be revamping the SBU and other designations.  Not sure how long the current process will be valid for.  Might need to research the stability of the current designation requirements.

**Comment by walshahi** [comment]
@karenBibb The latest version of the documentation is now live. This version of the docs is still a work in progress unfortunately, but it is a good start and will be a much better starting point than what was there before. The structure and layout is also much better.

Regarding this specific issue, the docs can be found here:

https://nasa.github.io/nasa-latex-docs/html/templates/doc-params.html#doccoversheet

Not much, but per our discussions I believe you know exactly how this works. More docs (and examples/screenshots) to come soon! In the meantime, in your existing document:

```
./support/buildPDF.py --update
```

Then add the `docCoverSheet` command and provide your PDF. `coversheet.pdf` is a sample file that you can try out first if you would like. It will be in the `support/` directory by default.
